name: DevOps Assessment CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  BACKEND_REPO: devops-assessment-backend
  FRONTEND_REPO: devops-assessment-frontend
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    # =========================
    # Checkout Code
    # =========================
    - name: Checkout Repository
      uses: actions/checkout@v5

    # =========================
    # Setup Node.js
    # =========================
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # =========================
    # Backend Install & Test
    # =========================
    - name: Install Backend Dependencies
      working-directory: backend
      run: npm install

    - name: Run Backend Tests
      working-directory: backend
      run: npm test

    # =========================
    # Frontend Install & Test
    # =========================
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm install

    - name: Run Frontend Tests
      working-directory: frontend
      run: npm test

    # =========================
    # AWS Login
    # =========================
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # =========================
    # Build & Push Backend
    # =========================
    - name: Build Backend Image
      run: |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:${{ github.sha }} ./backend

    - name: Push Backend Image
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:${{ github.sha }}

    # =========================
    # Build & Push Frontend
    # =========================
    - name: Build Frontend Image
      run: |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:${{ github.sha }} ./frontend

    - name: Push Frontend Image
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:${{ github.sha }}

    # =========================
    # Deploy to EKS
    # =========================
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    - name: Replace Image Tags in Kubernetes manifests
      run: |
        sed -i "s|IMAGE_TAG_PLACEHOLDER_BACKEND|${{ github.sha }}|g" k8s/backend-deployment.yaml
        sed -i "s|IMAGE_TAG_PLACEHOLDER_FRONTEND|${{ github.sha }}|g" k8s/frontend-deployment.yaml

    - name: Deploy to Kubernetes (EKS)
      run: |
        kubectl apply -f k8s/
